version: '3.8'

services:
  db:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - cluster_net
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: ./app
    container_name: app
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - cluster_net
    deploy:
      replicas: 3

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - cluster_net

networks:
  cluster_net:
    external: true

volumes:
  db_data:
